export const FETCH_CURRENCY = "FETCH_CURRENCY";
export const ADD_CURRENCY = "ADD_CURRENCY";
export const REMOVE_CURRENCY = "REMOVE_CURRENCY";
export const USD_RATE_ONCHANGE = "USD_RATE_ONCHANGE";
export const FETCH_CURRENCY_REQUEST = "FETCH_CURRENCY_REQUEST";
export const FETCH_CURRENCY_SUCCESS = "FETCH_CURRENCY_SUCCESS";
export const FETCH_CURRENCY_FAILURE = "FETCH_CURRENCY_FAILURE";
export const UPDATE_USD_VALUE = "UPDATE_USD_VALUE";